class SocketEvents {
  static const String IDOL_NOTIFICATION = 'IDOL_NOTIFICATION';
  static const String VIEWER_NOTIFICATION = 'VIEWER_NOTIFICATION';
  static const String VIEWER_TRANSACTION_DEPOSIT_VIA_CRYPTO_NEW = 'VIEWER_TRANSACTION_DEPOSIT_VIA_CRYPTO_NEW';
  static const String VIEWER_TRANSACTION_DEPOSIT_VIA_CRYPTO_SUCCESS = 'VIEWER_TRANSACTION_DEPOSIT_VIA_CRYPTO_SUCCESS';
  static const String VIEWER_TRANSACTION_DEPOSIT_VIA_CRYPTO_FAILED = 'VIEWER_TRANSACTION_DEPOSIT_VIA_CRYPTO_FAILED';
  static const String VIEWER_TRANSACTION_DEPOSIT_VIA_CRYPTO_FAILED_BY_MINIMUM_AMOUNT = 'VIEWER_TRANSACTION_DEPOSIT_VIA_CRYPTO_FAILED_BY_MINIMUM_AMOUNT';
  static const String VIEWER_TRANSACTION_DEPOSIT_VIA_CRYPTO_WAITING = 'VIEWER_TRANSACTION_DEPOSIT_VIA_CRYPTO_WAITING';
  static const String VIEWER_TRANSACTION_DEPOSIT_VIA_CRYPTO_DEL = 'VIEWER_TRANSACTION_DEPOSIT_VIA_CRYPTO_DEL';
}