name: glive_idol
description: App Glive Idol

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  common_module:
    path: ../modules/common/common_module

  user_management:
    path: ../modules/features/glive_idol/user_management

  live_stream:
    path: ../modules/features/glive_idol/live_stream

  flutter_modular: 5.0.2
  flutter_flavor: ^2.0.0
  flutter_dotenv: ^5.0.0
  logger: ^1.0.0
  firebase_core: 1.10.0
  firebase_messaging: 11.2.11
  awesome_notifications: ^0.6.21
  flutter_screenutil: 5.3.1
  shared_preferences: ^2.0.13
  zalo_flutter: 0.0.4
  shared_preferences_android: ^2.0.11
  shared_preferences_ios: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
  # flutter pub run flutter_native_splash:create
  flutter_native_splash: ^1.1.8+4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/level/
    - .env
    - .env.prod
    - .env.staging
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          style: normal
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
