name: user_management
description: user management
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  common_module:
    path: ../../../common/common_module

  live_stream:
    path: ../live_stream

  payment:
    path: ../payment

  level:
    path: ../level

  rtmp_publisher:
    path: ../../../libs/rtmp_publisher
  # Social Sign In
  google_sign_in: ^5.0.4
  flutter_facebook_auth: ^3.5.0
  sign_in_with_apple: ^3.2.0
  #  crypto: ^3.0.1

  cupertino_icons: ^1.0.2
  flutter_modular: 5.0.2
  dartz: 0.10.0-nullsafety.2
  validators: ^3.0.0
  logger: ^1.0.0
  mime: ^1.0.0
  get: ^4.3.8
  another_flushbar: ^1.10.24
  flutter_dotenv: ^5.0.0
  flutter_switch: ^0.3.2
  multi_image_picker2: ^5.0.2
  connectivity_plus: 2.2.1
#  camera_with_rtmp: ^0.3.2

  # The following adds the shared pref as a dependency in your application
  shared_preferences: ^2.0.13

  # A powerful Http client for Dart
  dio: ^4.0.0

  # An helper to easily exposes a value using InheritedWidget without having to write one.
  provider: ^5.0.0

  # This package provides internationalization and localization facilities, including message
  # translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.17.0

  # MobX is a library for reactively managing the state of your applications. Use the power of
  # observables, actions, and reactions to supercharge your Dart and Flutter apps.
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0

  equatable: ^2.0.3

  convex_bottom_bar: ^3.0.0

  permission_handler: 9.2.0
  camera: 0.9.4+16

  path: ^1.8.0

  flutter_countdown_timer: ^4.1.0
  image_picker: ^0.8.3+2
  image_cropper: 1.4.0

  firebase_core: 1.10.0
  firebase_messaging: 11.2.11

  intl_phone_field: ^2.1.0
  telephony: ^0.2.0

  # A composable, Future-based library for making HTTP requests.
  http: ^0.13.1
  zalo_flutter: 0.0.4
  badges: ^2.0.2
  flutter_screenutil: 5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.9.0
  # flutter pub run flutter_native_splash:create
  flutter_native_splash: ^1.1.8+4
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.1
  analyzer: ^1.5.0
  injectable_generator: ^1.3.0


flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.hita.glive.usermanagement
    iosBundleIdentifier: com.hita.glive.usermanagement
