name: glive
description: App Glive

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  common_module:
    path: ../modules/common/common_module

  user_management:
    path: ../modules/features/glive/user_management

  payment:
    path: ../modules/features/glive/payment

  get: 4.3.8
  flutter_modular: 5.0.2
  flutter_flavor: ^2.0.0
  flutter_dotenv: ^5.0.0
  logger: ^1.0.0
  firebase_core: 1.10.0
  firebase_messaging: 11.2.11
  awesome_notifications: ^0.6.21
  flutter_screenutil: 5.3.1
  shared_preferences: ^2.0.13
  zalo_flutter: 0.0.4
  shared_preferences_android: ^2.0.11
  shared_preferences_ios: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.9.2
  # flutter pub run flutter_native_splash:create
  flutter_native_splash: ^2.1.1

flutter_icons:
  image_path: "assets/icons/ic_appicon.png"
  android: true
  ios: true

flutter_native_splash:
  image: "assets/icons/ic_launcher.png"
  color: "#FFFFFF"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/level/
    - assets/icons/payment/
    - assets/token-abi.json
    - .env
    - .env.prod
    - .env.staging
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          style: normal
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

