name: common_module
description: common module
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  package_info: ^2.0.2
  carousel_slider: ^4.0.0
  flutter_modular: 5.0.2
  flutter_flavor: ^2.0.0
  flutter_dotenv: ^5.0.0
  firebase_storage: ^8.1.3
  firebase_core: 1.10.0
  firebase_database: ^7.1.1
  cloud_firestore: ^2.2.2
  device_info_plus: ^3.2.3
  another_flushbar: ^1.10.24
  flutter_screenutil: 5.3.1
  logger: ^1.0.0
  email_validator: 2.0.1
  connectivity_plus: 2.2.1
  cached_network_image: ^3.2.0
  firebase_messaging: 11.2.11
  awesome_notifications: ^0.6.21
  numeral: ^2.0.0

  # An helper to easily exposes a value using InheritedWidget without having to write one.
  sembast: ^3.0.2
  path_provider: ^2.0.1

  # XXTEA is a fast and secure encryption algorithm. This is a XXTEA library for Dart.
  xxtea: ^2.1.0
  # translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.17.0
  get: ^4.3.8
  equatable: ^2.0.3
  dartz: 0.10.0-nullsafety.2
  shared_preferences: ^2.0.13
  dio: ^4.0.0
  socket_io_client: ^1.0.2
  rxdart: 0.27.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.hita.glive.common
    iosBundleIdentifier: com.hita.glive.common
